#image with php and apache
FROM php:7.0-apache

#copy the current directory contents into the container at /var/www/html
COPY src/ /var/www/html

#make port 80 available to the world outside this container
EXPOSE 80